server:
  port: 3000

gateway:
  api:
    key: ${GATEWAY_API_KEY}

spring:
  application:
    name: "dxs-gateway-api"
  cloud:
    gateway:
      routes:
        - id: auth-public
          uri: http://localhost:3008
          predicates:
            - Path=/public/api/v1/auth/**
        - id: auth-private
          uri: http://localhost:3008
          predicates:
            - Path=/private/api/v1/auth/**
          filters:
            - name: AuthenticationFilter
              args:
                authenticationUri: http://localhost:3008/private/api/v1/auth/verify-token

